/*
 * HackPac - OpenAPI 3.0
 * Pacman api server
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HackPacOpenApi30);
  }
}(this, function(expect, HackPacOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HackPacOpenApi30.ControllerApi();
  });

  describe('(package)', function() {
    describe('ControllerApi', function() {
      describe('controllerControllerIdDirectionPost', function() {
        it('should call controllerControllerIdDirectionPost successfully', function(done) {
          // TODO: uncomment, update parameter values for controllerControllerIdDirectionPost call
          /*
          var opts = {};

          instance.controllerControllerIdDirectionPost(controllerId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('controllerGet', function() {
        it('should call controllerGet successfully', function(done) {
          // TODO: uncomment controllerGet call and complete the assertions
          /*

          instance.controllerGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(HackPacOpenApi30.Controller);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
