# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DirectionUpdate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, direction: str=None):  # noqa: E501
        """DirectionUpdate - a model defined in Swagger

        :param id: The id of this DirectionUpdate.  # noqa: E501
        :type id: int
        :param direction: The direction of this DirectionUpdate.  # noqa: E501
        :type direction: str
        """
        self.swagger_types = {
            'id': int,
            'direction': str
        }

        self.attribute_map = {
            'id': 'id',
            'direction': 'direction'
        }
        self._id = id
        self._direction = direction

    @classmethod
    def from_dict(cls, dikt) -> 'DirectionUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DirectionUpdate of this DirectionUpdate.  # noqa: E501
        :rtype: DirectionUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this DirectionUpdate.


        :return: The id of this DirectionUpdate.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this DirectionUpdate.


        :param id: The id of this DirectionUpdate.
        :type id: int
        """

        self._id = id

    @property
    def direction(self) -> str:
        """Gets the direction of this DirectionUpdate.


        :return: The direction of this DirectionUpdate.
        :rtype: str
        """
        return self._direction

    @direction.setter
    def direction(self, direction: str):
        """Sets the direction of this DirectionUpdate.


        :param direction: The direction of this DirectionUpdate.
        :type direction: str
        """

        self._direction = direction
