# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Update(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, update_type: str=None, update_details: object=None):  # noqa: E501
        """Update - a model defined in Swagger

        :param update_type: The update_type of this Update.  # noqa: E501
        :type update_type: str
        :param update_details: The update_details of this Update.  # noqa: E501
        :type update_details: object
        """
        self.swagger_types = {
            'update_type': str,
            'update_details': object
        }

        self.attribute_map = {
            'update_type': 'updateType',
            'update_details': 'updateDetails'
        }
        self._update_type = update_type
        self._update_details = update_details

    @classmethod
    def from_dict(cls, dikt) -> 'Update':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Update of this Update.  # noqa: E501
        :rtype: Update
        """
        return util.deserialize_model(dikt, cls)

    @property
    def update_type(self) -> str:
        """Gets the update_type of this Update.


        :return: The update_type of this Update.
        :rtype: str
        """
        return self._update_type

    @update_type.setter
    def update_type(self, update_type: str):
        """Sets the update_type of this Update.


        :param update_type: The update_type of this Update.
        :type update_type: str
        """

        self._update_type = update_type

    @property
    def update_details(self) -> object:
        """Gets the update_details of this Update.


        :return: The update_details of this Update.
        :rtype: object
        """
        return self._update_details

    @update_details.setter
    def update_details(self, update_details: object):
        """Sets the update_details of this Update.


        :param update_details: The update_details of this Update.
        :type update_details: object
        """

        self._update_details = update_details
