/*
 * HackPac - OpenAPI 3.0
 * Pacman api server
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HackPacOpenApi30);
  }
}(this, function(expect, HackPacOpenApi30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('DirectionUpdate', function() {
      beforeEach(function() {
        instance = new HackPacOpenApi30.DirectionUpdate();
      });

      it('should create an instance of DirectionUpdate', function() {
        // TODO: update the code to test DirectionUpdate
        expect(instance).to.be.a(HackPacOpenApi30.DirectionUpdate);
      });

      it('should have the property direction (base name: "direction")', function() {
        // TODO: update the code to test the property direction
        expect(instance).to.have.property('direction');
        // expect(instance.direction).to.be(expectedValueLiteral);
      });

    });
  });

}));
