/*
 * HackPac - OpenAPI 3.0
 * Pacman api server
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Controller model module.
 * @module model/Controller
 * @version 1.0.11
 */
export class Controller {
  /**
   * Constructs a new <code>Controller</code>.
   * @alias module:model/Controller
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Controller</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Controller} obj Optional instance to populate.
   * @return {module:model/Controller} The populated <code>Controller</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Controller();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Controller.prototype.id = undefined;

