/*
 * HackPac - OpenAPI 3.0
 * Pacman api server
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.50
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DirectionUpdate model module.
 * @module model/DirectionUpdate
 * @version 1.0.11
 */
export class DirectionUpdate {
  /**
   * Constructs a new <code>DirectionUpdate</code>.
   * @alias module:model/DirectionUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DirectionUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DirectionUpdate} obj Optional instance to populate.
   * @return {module:model/DirectionUpdate} The populated <code>DirectionUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DirectionUpdate();
      if (data.hasOwnProperty('direction'))
        obj.direction = ApiClient.convertToType(data['direction'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} direction
 */
DirectionUpdate.prototype.direction = undefined;

